from __future__ import annotations

from pathlib import Path

PACKAGE_VERSION = "0.1.0"
ECM_PATH = "ecm"
DATA_DIR = Path("data")
NUMBERS_DIR = DATA_DIR / "numbers"
EXPERIMENTS_DIR = DATA_DIR / "experiments"

DEFAULT_B1_RANGE: tuple[float, float] = (1e3, 1e9)
DEFAULT_B2_RANGE: tuple[int, int] = (1_000, 100_000_000_000)
DEFAULT_RATIO_MAX = 100.0
DEFAULT_CURVES_PER_N = 50
DEFAULT_VALIDATION_CURVES_PER_N = 100
DEFAULT_POPSIZE = 16
DEFAULT_MAXITER = 25
DEFAULT_SEED = 42
DEFAULT_COFACTOR_DIGITS = 90
DEFAULT_TRAIN_COUNT = 20
DEFAULT_CONTROL_COUNT = 20
DEFAULT_CURVE_TIMEOUT_SEC: float | None = None
DEFAULT_WORKERS = -1
DEFAULT_PREFIX = "dset"

DEFAULT_BASELINE_TARGET_DIGITS = 20
DEFAULT_BASELINE_B1 = 11_000
DEFAULT_BASELINE_B2 = 220_000
